In [1]:
# Declarations
import glob
import json
import os
import numpy as np
import pandas as pd
import re

from os.path import basename

In [2]:
nameFileV = []
pathFileV = []
rootFileV = []
nameFileM = []
pathFileM = []
rootFileM = []
nameFileS = []
pathFileS = []
rootFileS = []
nameFileSV = []
pathFileSV = []
rootFileSV = []

path = os.getcwd()
for root, dirs, files in os.walk(path):
    for file in files:
        if file.endswith("ScalarSize.csv"):
            nameFileS.append(file)
            pathFileS.append(os.path.join(root, file))
            rootFileS.append(root)
        elif file.endswith("ScalarVariable.csv"):
            nameFileSV.append(file)
            pathFileSV.append(os.path.join(root, file))
            rootFileSV.append(root)
        elif file.endswith("Vector.csv"):
            nameFileV.append(file)
            pathFileV.append(os.path.join(root, file))
            rootFileV.append(root)
        elif file.endswith("Matrix.csv"):
            nameFileM.append(file)
            pathFileM.append(os.path.join(root, file))
            rootFileM.append(root)

In [3]:
# ScalarSize file
for i in range(0, len(pathFileS)):
    path = pathFileS[i]
    try:
        dfSTemp = pd.read_csv(path, sep=',',engine='python',header=None)
    except:
        print(path)
    dfSTemp = dfSTemp.rename(columns={0:'ID_VAL'})    
    
    for j in range(1, len(dfSTemp.columns)):
        dfSTemp = dfSTemp.rename(columns={j:'SS_VAL_'+str(j)})
    
    if os.name == 'nt':
        spR = rootFileS[i].split('\\')
    else:
        spR = rootFileS[i].split('/')
    datatype = spR[-2]
    device = spR[-7]
    board = spR[-6]
    function = spR[-4]
    number = int(spR[-5].split('x')[0])
    dfSTemp['DEVICE'] = device
    dfSTemp['BOARD'] = board
    dfSTemp['FUNCTION'] = function
    dfSTemp['DATA_TYPE'] = datatype
    dfSTemp['ID_VAL'] = dfSTemp['ID_VAL'].astype(str)
    dfSTemp['ID_VAL'] = dfSTemp['ID_VAL'].map(lambda x: x.lstrip('values_'))
    dfSTemp['ID_VAL'] = dfSTemp['ID_VAL'].astype(int)
    dfSTemp.sort_values('ID_VAL')
    
    if i == 0:
        dfSTot = dfSTemp
    else:
        frames = [dfSTot, dfSTemp]
        dfSTot = pd.concat(frames)
        
dfSTot = dfSTot.fillna(0)

In [4]:
dfSTot

    ID_VAL  SS_VAL_1 DEVICE                     BOARD       FUNCTION DATA_TYPE
0       27         2  Bambu  5SGXEA7N2F45C1-Stratix-V  insertionsort    int8_t
1       84        16  Bambu  5SGXEA7N2F45C1-Stratix-V  insertionsort    int8_t
2       65         5  Bambu  5SGXEA7N2F45C1-Stratix-V  insertionsort    int8_t
3       96        27  Bambu  5SGXEA7N2F45C1-Stratix-V  insertionsort    int8_t
4       28        21  Bambu  5SGXEA7N2F45C1-Stratix-V  insertionsort    int8_t
..     ...       ...    ...                       ...            ...       ...
95      10        13  Bambu  5SGXEA7N2F45C1-Stratix-V  floydwarshall    int8_t
96      67        27  Bambu  5SGXEA7N2F45C1-Stratix-V  floydwarshall    int8_t
97      35         7  Bambu  5SGXEA7N2F45C1-Stratix-V  floydwarshall    int8_t
98      30        27  Bambu  5SGXEA7N2F45C1-Stratix-V  floydwarshall    int8_t
99       4        13  Bambu  5SGXEA7N2F45C1-Stratix-V  floydwarshall    int8_t

[1500 rows x 6 columns]

In [5]:
# ScalarVariable file
for i in range(0, len(pathFileSV)):
    path = pathFileSV[i]
    try:
        dfSVTemp = pd.read_csv(path, sep=',',engine='python',header=None)
    except:
        print(path)
    dfSVTemp = dfSVTemp.rename(columns={0:'ID_VAL'})
    
    for j in range(1, len(dfSVTemp.columns)):
        dfSVTemp = dfSVTemp.rename(columns={j:'SV_VAL_'+str(j)})
        
    if os.name == 'nt':
        spR = rootFileSV[i].split('\\')
    else:
        spR = rootFileSV[i].split('/')
    datatype = spR[-2]
    device = spR[-7]
    board = spR[-6]
    function = spR[-4]
    dfSVTemp['DEVICE'] = device
    dfSVTemp['BOARD'] = board
    dfSVTemp['FUNCTION'] = function
    dfSVTemp['DATA_TYPE'] = datatype
    dfSVTemp['ID_VAL'] = dfSVTemp['ID_VAL'].astype(str)
    dfSVTemp['ID_VAL'] = dfSVTemp['ID_VAL'].map(lambda x: x.lstrip('values_'))
    dfSVTemp['ID_VAL'] = dfSVTemp['ID_VAL'].astype(int)
    dfSVTemp.sort_values('ID_VAL')
    
    if i == 0:
        dfSVTot = dfSVTemp
    else:
        frames = [dfSVTot, dfSVTemp]
        dfSVTot = pd.concat(frames)

dfSVTot = dfSVTot.fillna(0)

In [6]:
dfSVTot

,ID_VAL,SV_VAL_1,DEVICE,BOARD,FUNCTION,DATA_TYPE,SV_VAL_2
0,27,10,Bambu,5SGXEA7N2F45C1-Stratix-V,park_miller,int8_t,0.0
1,84,4,Bambu,5SGXEA7N2F45C1-Stratix-V,park_miller,int8_t,0.0
2,65,-4,Bambu,5SGXEA7N2F45C1-Stratix-V,park_miller,int8_t,0.0
3,96,3,Bambu,5SGXEA7N2F45C1-Stratix-V,park_miller,int8_t,0.0
4,28,-34,Bambu,5SGXEA7N2F45C1-Stratix-V,park_miller,int8_t,0.0
...,...,...,...,...,...,...,...
95,10,3,Bambu,5SGXEA7N2F45C1-Stratix-V,fft,int8_t,0.0
96,67,2,Bambu,5SGXEA7N2F45C1-Stratix-V,fft,int8_t,-1.0
97,35,9,Bambu,5SGXEA7N2F45C1-Stratix-V,fft,int8_t,0.0
98,30,9,Bambu,5SGXEA7N2F45C1-Stratix-V,fft,int8_t,0.0
99,4,3,Bambu,5SGXEA7N2F45C1-Stratix-V,fft,int8_t,1.0

In [7]:
# Vector file
for i in range(0, len(pathFileV)):
    path = pathFileV[i]
    dfVTemp = pd.read_csv(path, sep=',',engine='python', header=None)
    dfVTemp = dfVTemp.rename(columns={0:'ID_VAL'})
    
    for j in range(1, len(dfVTemp.columns)):
        dfVTemp = dfVTemp.rename(columns={j:'V_VAL_'+str(j)})
    
    if os.name == 'nt':
        spR = rootFileV[i].split('\\')
    else:
        spR = rootFileV[i].split('/')
    datatype = spR[-2]
    device = spR[-7]
    board = spR[-6]
    function = spR[-4]
    dfVTemp['DEVICE'] = device
    dfVTemp['BOARD'] = board
    dfVTemp['FUNCTION'] = function
    dfVTemp['DATA_TYPE'] = datatype
    dfVTemp['ID_VAL'] = dfVTemp['ID_VAL'].map(lambda x: x.lstrip('values_'))
    dfVTemp['ID_VAL'] = dfVTemp['ID_VAL'].astype(int)
    dfVTemp.sort_values('ID_VAL')
    
    if i == 0:
        dfVTot = dfVTemp
    else:
        frames = [dfVTot, dfVTemp]
        dfVTot = pd.concat(frames)

dfVTot = dfVTot.fillna(0)

In [8]:
dfVTot

,ID_VAL,V_VAL_1,V_VAL_2,V_VAL_3,V_VAL_4,V_VAL_5,V_VAL_6,V_VAL_7,V_VAL_8,V_VAL_9,...,V_VAL_23,V_VAL_24,V_VAL_25,V_VAL_26,V_VAL_27,V_VAL_28,DEVICE,BOARD,FUNCTION,DATA_TYPE
0,27,-43,-22,0,0,0,0,0,0,0,...,0,0,0,0,0,0,Bambu,5SGXEA7N2F45C1-Stratix-V,insertionsort,int8_t
1,84,-124,126,82,7,-16,-106,-2,-22,-1,...,0,0,0,0,0,0,Bambu,5SGXEA7N2F45C1-Stratix-V,insertionsort,int8_t
2,65,48,-111,36,97,-3,0,0,0,0,...,0,0,0,0,0,0,Bambu,5SGXEA7N2F45C1-Stratix-V,insertionsort,int8_t
3,96,15,95,6,9,93,-66,19,46,-62,...,-98,9,17,-113,123,0,Bambu,5SGXEA7N2F45C1-Stratix-V,insertionsort,int8_t
4,28,124,55,111,-17,47,56,106,49,9,...,0,0,0,0,0,0,Bambu,5SGXEA7N2F45C1-Stratix-V,insertionsort,int8_t
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,10,113,-75,124,-106,-120,126,-66,-97,0,...,0,0,0,0,0,0,Bambu,5SGXEA7N2F45C1-Stratix-V,fft,int8_t
96,67,106,96,-98,-85,19,70,-35,-120,0,...,0,0,0,0,0,0,Bambu,5SGXEA7N2F45C1-Stratix-V,fft,int8_t
97,35,69,29,-44,45,-73,-122,-96,-63,0,...,0,0,0,0,0,0,Bambu,5SGXEA7N2F45C1-Stratix-V,fft,int8_t
98,30,3,14,-54,-112,-51,-71,0,0,0,...,0,0,0,0,0,0,Bambu,5SGXEA7N2F45C1-Stratix-V,fft,int8_t
99,4,-93,40,-53,46,-96,-77,0,0,0,...,0,0,0,0,0,0,Bambu,5SGXEA7N2F45C1-Stratix-V,fft,int8_t

In [9]:
# Matrix file
pathFileM.pop(0)
rootFileM.pop(0)

for i in range(0, len(pathFileM)):
    path = pathFileM[i]
    dfMTemp = pd.read_csv(path, sep=',',engine='python', header=None)
    dfMTemp = dfMTemp.rename(columns={0:'ID_VAL'})
    
    for j in range(1, len(dfMTemp.columns)):
        dfMTemp = dfMTemp.rename(columns={j:'M_VAL_'+str(j)})
    
    if os.name == 'nt':
        spR = rootFileM[i].split('\\')
    else:
        spR = rootFileM[i].split('/')
    datatype = spR[-2]
    device = spR[-7]
    board = spR[-6]
    function = spR[-4]
    dfMTemp['DEVICE'] = device
    dfMTemp['BOARD'] = board
    dfMTemp['FUNCTION'] = function
    dfMTemp['DATA_TYPE'] = datatype
    dfMTemp['ID_VAL'] = dfMTemp['ID_VAL'].map(lambda x: x.lstrip('values_'))
    dfMTemp['ID_VAL'] = dfMTemp['ID_VAL'].astype(int)
    dfMTemp.sort_values('ID_VAL')
    
    if i == 0:
        dfMTot = dfMTemp
    else:
        frames = [dfMTot, dfMTemp]
        dfMTot = pd.concat(frames)

dfMTot = dfMTot.fillna(0)

In [10]:
dfMTot

,ID_VAL,M_VAL_1,M_VAL_2,M_VAL_3,M_VAL_4,M_VAL_5,M_VAL_6,M_VAL_7,M_VAL_8,M_VAL_9,...,M_VAL_27,M_VAL_28,M_VAL_29,M_VAL_30,M_VAL_31,M_VAL_32,DEVICE,BOARD,FUNCTION,DATA_TYPE
0,15,0.00000,6.673624,0.000000,0.0,9.752675,20.225321,10.664698,18.714132,3.204332,...,0.000000,0.000000,3.860665,12.562267,2.437915,4.678443,Bambu,5SGXEA7N2F45C1-Stratix-V,astar,int8_t
1,17,0.00000,7.120653,0.000000,0.0,15.147158,12.659382,18.928076,19.928469,2.967601,...,3.632953,3.226790,1.373455,7.792701,5.489540,5.188308,Bambu,5SGXEA7N2F45C1-Stratix-V,astar,int8_t
2,16,3.42476,5.125723,0.000000,0.0,6.434064,15.769947,16.301394,12.086406,1.760492,...,2.058318,0.499923,0.817023,8.039990,9.769136,7.036201,Bambu,5SGXEA7N2F45C1-Stratix-V,astar,int8_t
3,92,0.00000,9.021723,4.384820,0.0,39.816185,26.890474,0.000000,38.709915,1.898666,...,0.000000,0.000000,59.526642,26.213203,9.282681,49.436218,Bambu,5SGXEA7N2F45C1-Stratix-V,astar,int8_t
4,55,0.00000,7.383680,0.000000,0.0,28.385466,20.939554,24.100790,9.792846,0.000000,...,0.000000,0.000000,17.304041,18.244257,16.797968,21.308512,Bambu,5SGXEA7N2F45C1-Stratix-V,astar,int8_t
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,61,0.00000,0.000000,5.623025,0.0,3.643740,0.000000,14.505861,0.441485,0.000000,...,0.073415,0.901956,3.900461,5.504440,4.159144,0.256412,Bambu,5SGXEA7N2F45C1-Stratix-V,floydwarshall,int8_t
96,11,0.00000,0.000000,0.000000,0.0,34.288471,15.610343,17.440035,30.926899,0.000000,...,0.000000,0.000000,26.439558,9.607828,24.806917,16.335993,Bambu,5SGXEA7N2F45C1-Stratix-V,floydwarshall,int8_t
97,87,0.00000,0.000000,1.916955,0.0,18.987206,6.378043,21.329903,3.561712,0.000000,...,4.812780,0.000000,7.291459,0.000000,16.835188,1.913184,Bambu,5SGXEA7N2F45C1-Stratix-V,floydwarshall,int8_t
98,5,0.00000,0.000000,0.000000,0.0,39.657566,11.693703,20.712490,31.282854,0.000000,...,0.000000,0.000000,55.922596,14.846810,28.495367,26.935823,Bambu,5SGXEA7N2F45C1-Stratix-V,floydwarshall,int8_t
99,75,0.00000,2.785650,0.000000,0.0,4.055437,6.974123,9.838006,0.304113,0.000000,...,0.000000,1.556340,1.587680,0.956396,0.000000,0.000000,Bambu,5SGXEA7N2F45C1-Stratix-V,floydwarshall,int8_t

In [11]:
dfSTot = dfSTot.reset_index(drop=True)
dfSVTot = dfSVTot.reset_index(drop=True)
dfVTot = dfVTot.reset_index(drop=True)
dfMTot = dfMTot.reset_index(drop=True)

In [12]:
first_column = dfSTot.pop("DEVICE")
dfSTot.insert(0, 'value', first_column)
dfSTot = dfSTot.rename(columns={'value':'DEVICE'})

first_column = dfSTot.pop("BOARD")
dfSTot.insert(1, 'value', first_column)
dfSTot = dfSTot.rename(columns={'value':'BOARD'})

first_column = dfSTot.pop("FUNCTION")
dfSTot.insert(2, 'value', first_column)
dfSTot = dfSTot.rename(columns={'value':'FUNCTION'})

first_column = dfSTot.pop("DATA_TYPE")
dfSTot.insert(3, 'value', first_column)
dfSTot = dfSTot.rename(columns={'value':'DATA_TYPE'})

In [13]:
dfSTot

,DEVICE,BOARD,FUNCTION,DATA_TYPE,ID_VAL,SS_VAL_1
0,Bambu,5SGXEA7N2F45C1-Stratix-V,insertionsort,int8_t,27,2
1,Bambu,5SGXEA7N2F45C1-Stratix-V,insertionsort,int8_t,84,16
2,Bambu,5SGXEA7N2F45C1-Stratix-V,insertionsort,int8_t,65,5
3,Bambu,5SGXEA7N2F45C1-Stratix-V,insertionsort,int8_t,96,27
4,Bambu,5SGXEA7N2F45C1-Stratix-V,insertionsort,int8_t,28,21
...,...,...,...,...,...,...
1495,Bambu,5SGXEA7N2F45C1-Stratix-V,floydwarshall,int8_t,10,13
1496,Bambu,5SGXEA7N2F45C1-Stratix-V,floydwarshall,int8_t,67,27
1497,Bambu,5SGXEA7N2F45C1-Stratix-V,floydwarshall,int8_t,35,7
1498,Bambu,5SGXEA7N2F45C1-Stratix-V,floydwarshall,int8_t,30,27
1499,Bambu,5SGXEA7N2F45C1-Stratix-V,floydwarshall,int8_t,4,13

In [14]:
first_column = dfSVTot.pop("DEVICE")
dfSVTot.insert(0, 'value', first_column)
dfSVTot = dfSVTot.rename(columns={'value':'DEVICE'})

first_column = dfSVTot.pop("BOARD")
dfSVTot.insert(1, 'value', first_column)
dfSVTot = dfSVTot.rename(columns={'value':'BOARD'})

first_column = dfSVTot.pop("FUNCTION")
dfSVTot.insert(2, 'value', first_column)
dfSVTot = dfSVTot.rename(columns={'value':'FUNCTION'})

first_column = dfSVTot.pop("DATA_TYPE")
dfSVTot.insert(3, 'value', first_column)
dfSVTot = dfSVTot.rename(columns={'value':'DATA_TYPE'})

In [15]:
dfSVTot

,DEVICE,BOARD,FUNCTION,DATA_TYPE,ID_VAL,SV_VAL_1,SV_VAL_2
0,Bambu,5SGXEA7N2F45C1-Stratix-V,park_miller,int8_t,27,10,0.0
1,Bambu,5SGXEA7N2F45C1-Stratix-V,park_miller,int8_t,84,4,0.0
2,Bambu,5SGXEA7N2F45C1-Stratix-V,park_miller,int8_t,65,-4,0.0
3,Bambu,5SGXEA7N2F45C1-Stratix-V,park_miller,int8_t,96,3,0.0
4,Bambu,5SGXEA7N2F45C1-Stratix-V,park_miller,int8_t,28,-34,0.0
...,...,...,...,...,...,...,...
795,Bambu,5SGXEA7N2F45C1-Stratix-V,fft,int8_t,10,3,0.0
796,Bambu,5SGXEA7N2F45C1-Stratix-V,fft,int8_t,67,2,-1.0
797,Bambu,5SGXEA7N2F45C1-Stratix-V,fft,int8_t,35,9,0.0
798,Bambu,5SGXEA7N2F45C1-Stratix-V,fft,int8_t,30,9,0.0
799,Bambu,5SGXEA7N2F45C1-Stratix-V,fft,int8_t,4,3,1.0

In [16]:
first_column = dfVTot.pop("DEVICE")
dfVTot.insert(0, 'value', first_column)
dfVTot = dfVTot.rename(columns={'value':'DEVICE'})

first_column = dfVTot.pop("BOARD")
dfVTot.insert(1, 'value', first_column)
dfVTot = dfVTot.rename(columns={'value':'BOARD'})

first_column = dfVTot.pop("FUNCTION")
dfVTot.insert(2, 'value', first_column)
dfVTot = dfVTot.rename(columns={'value':'FUNCTION'})

first_column = dfVTot.pop("DATA_TYPE")
dfVTot.insert(3, 'value', first_column)
dfVTot = dfVTot.rename(columns={'value':'DATA_TYPE'})

In [17]:
dfVTot

,DEVICE,BOARD,FUNCTION,DATA_TYPE,ID_VAL,V_VAL_1,V_VAL_2,V_VAL_3,V_VAL_4,V_VAL_5,...,V_VAL_19,V_VAL_20,V_VAL_21,V_VAL_22,V_VAL_23,V_VAL_24,V_VAL_25,V_VAL_26,V_VAL_27,V_VAL_28
0,Bambu,5SGXEA7N2F45C1-Stratix-V,insertionsort,int8_t,27,-43,-22,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Bambu,5SGXEA7N2F45C1-Stratix-V,insertionsort,int8_t,84,-124,126,82,7,-16,...,0,0,0,0,0,0,0,0,0,0
2,Bambu,5SGXEA7N2F45C1-Stratix-V,insertionsort,int8_t,65,48,-111,36,97,-3,...,0,0,0,0,0,0,0,0,0,0
3,Bambu,5SGXEA7N2F45C1-Stratix-V,insertionsort,int8_t,96,15,95,6,9,93,...,7,-41,-42,-116,-98,9,17,-113,123,0
4,Bambu,5SGXEA7N2F45C1-Stratix-V,insertionsort,int8_t,28,124,55,111,-17,47,...,-72,36,-57,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1095,Bambu,5SGXEA7N2F45C1-Stratix-V,fft,int8_t,10,113,-75,124,-106,-120,...,0,0,0,0,0,0,0,0,0,0
1096,Bambu,5SGXEA7N2F45C1-Stratix-V,fft,int8_t,67,106,96,-98,-85,19,...,0,0,0,0,0,0,0,0,0,0
1097,Bambu,5SGXEA7N2F45C1-Stratix-V,fft,int8_t,35,69,29,-44,45,-73,...,0,0,0,0,0,0,0,0,0,0
1098,Bambu,5SGXEA7N2F45C1-Stratix-V,fft,int8_t,30,3,14,-54,-112,-51,...,0,0,0,0,0,0,0,0,0,0
1099,Bambu,5SGXEA7N2F45C1-Stratix-V,fft,int8_t,4,-93,40,-53,46,-96,...,0,0,0,0,0,0,0,0,0,0

In [18]:
first_column = dfMTot.pop("DEVICE")
dfMTot.insert(0, 'value', first_column)
dfMTot = dfMTot.rename(columns={'value':'DEVICE'})

first_column = dfMTot.pop("BOARD")
dfMTot.insert(1, 'value', first_column)
dfMTot = dfMTot.rename(columns={'value':'BOARD'})

first_column = dfMTot.pop("FUNCTION")
dfMTot.insert(2, 'value', first_column)
dfMTot = dfMTot.rename(columns={'value':'FUNCTION'})

first_column = dfMTot.pop("DATA_TYPE")
dfMTot.insert(3, 'value', first_column)
dfMTot = dfMTot.rename(columns={'value':'DATA_TYPE'})

In [19]:
dfMTot

,DEVICE,BOARD,FUNCTION,DATA_TYPE,ID_VAL,M_VAL_1,M_VAL_2,M_VAL_3,M_VAL_4,M_VAL_5,...,M_VAL_23,M_VAL_24,M_VAL_25,M_VAL_26,M_VAL_27,M_VAL_28,M_VAL_29,M_VAL_30,M_VAL_31,M_VAL_32
0,Bambu,5SGXEA7N2F45C1-Stratix-V,astar,int8_t,15,0.00000,6.673624,0.000000,0.0,9.752675,...,14.253813,3.278602,4.692426,8.556578,0.000000,0.000000,3.860665,12.562267,2.437915,4.678443
1,Bambu,5SGXEA7N2F45C1-Stratix-V,astar,int8_t,17,0.00000,7.120653,0.000000,0.0,15.147158,...,7.208503,2.554065,1.144220,1.552350,3.632953,3.226790,1.373455,7.792701,5.489540,5.188308
2,Bambu,5SGXEA7N2F45C1-Stratix-V,astar,int8_t,16,3.42476,5.125723,0.000000,0.0,6.434064,...,14.633278,4.696711,2.044797,2.642573,2.058318,0.499923,0.817023,8.039990,9.769136,7.036201
3,Bambu,5SGXEA7N2F45C1-Stratix-V,astar,int8_t,92,0.00000,9.021723,4.384820,0.0,39.816185,...,19.923515,27.577795,0.000000,17.428640,0.000000,0.000000,59.526642,26.213203,9.282681,49.436218
4,Bambu,5SGXEA7N2F45C1-Stratix-V,astar,int8_t,55,0.00000,7.383680,0.000000,0.0,28.385466,...,33.182285,25.670786,0.000000,0.000000,0.000000,0.000000,17.304041,18.244257,16.797968,21.308512
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,Bambu,5SGXEA7N2F45C1-Stratix-V,floydwarshall,int8_t,61,0.00000,0.000000,5.623025,0.0,3.643740,...,3.524200,0.000000,0.338492,0.269614,0.073415,0.901956,3.900461,5.504440,4.159144,0.256412
596,Bambu,5SGXEA7N2F45C1-Stratix-V,floydwarshall,int8_t,11,0.00000,0.000000,0.000000,0.0,34.288471,...,32.075207,16.423319,0.000000,0.000000,0.000000,0.000000,26.439558,9.607828,24.806917,16.335993
597,Bambu,5SGXEA7N2F45C1-Stratix-V,floydwarshall,int8_t,87,0.00000,0.000000,1.916955,0.0,18.987206,...,14.012575,0.000000,0.000000,0.000000,4.812780,0.000000,7.291459,0.000000,16.835188,1.913184
598,Bambu,5SGXEA7N2F45C1-Stratix-V,floydwarshall,int8_t,5,0.00000,0.000000,0.000000,0.0,39.657566,...,24.813414,23.158932,0.000000,12.147664,0.000000,0.000000,55.922596,14.846810,28.495367,26.935823
599,Bambu,5SGXEA7N2F45C1-Stratix-V,floydwarshall,int8_t,75,0.00000,2.785650,0.000000,0.0,4.055437,...,3.166389,0.000000,1.349796,0.647400,0.000000,1.556340,1.587680,0.956396,0.000000,0.000000

In [20]:
dfSTot.to_csv("dfSTot.csv", sep=';')
dfSVTot.to_csv("dfSVTot.csv", sep=';')
dfVTot.to_csv("dfVTot.csv", sep=';')
dfMTot.to_csv("dfMTot.csv", sep=';')

In [21]:
dfTPM = pd.read_csv("TotalParameterMatrixBambu.csv", sep=';')
del dfTPM['Unnamed: 0']

In [22]:
dfTot1 = pd.merge(dfTPM,dfSTot,how='left',on=['DEVICE','BOARD','FUNCTION','DATA_TYPE','ID_VAL'])

In [23]:
dfTot1.columns

Index(['DEVICE', 'BOARD', 'FUNCTION', 'DATA_TYPE', 'ID_VAL', 'DSP', 'BRAM',
       'Flip_Flop', 'Area', 'min_Slack', 'Max_Freq', 'Time', 'Energy',
       'BugsDelivered', 'DifficultyLevel', 'DistinctOperands',
       'DistinctOperators', 'Effort', 'ProgramLength', 'ProgramLevel',
       'ProgramVolume', 'TimeToImplement', 'TotalOperators', 'Total_Operands',
       'VocabularySize', 'Sloc', 'DecisionPoint', 'GlobalVariables', 'If',
       'Loop', 'Goto', 'Assignment', 'ExitPoint', 'Function', 'FunctionCall',
       'PointerDereferencing', 'CyclomaticComplexity',
       'SyntacticallyReachableFunctions', 'SemanticallyReachedFunctions',
       'CoverageEstimation', 'SCALAR_INPUT', 'RANGE_SCALAR_VALUES',
       'SCALAR_INDEX_INPUT', 'RANGE_SCALAR_INDEX_VALUES', 'ARRAY_INPUT',
       'RANGE_ARRAY_INPUT', 'cInstr', 'assemblyInstr', 'clockCycles', 'CC4CS',
       'Bugs_Delivered', 'SS_VAL_1'],
      dtype='object')

In [24]:
dfTot2 = pd.merge(dfTot1,dfSVTot,how='left',on=['DEVICE','BOARD','FUNCTION','DATA_TYPE','ID_VAL'])

In [25]:
dfTot2.columns

Index(['DEVICE', 'BOARD', 'FUNCTION', 'DATA_TYPE', 'ID_VAL', 'DSP', 'BRAM',
       'Flip_Flop', 'Area', 'min_Slack', 'Max_Freq', 'Time', 'Energy',
       'BugsDelivered', 'DifficultyLevel', 'DistinctOperands',
       'DistinctOperators', 'Effort', 'ProgramLength', 'ProgramLevel',
       'ProgramVolume', 'TimeToImplement', 'TotalOperators', 'Total_Operands',
       'VocabularySize', 'Sloc', 'DecisionPoint', 'GlobalVariables', 'If',
       'Loop', 'Goto', 'Assignment', 'ExitPoint', 'Function', 'FunctionCall',
       'PointerDereferencing', 'CyclomaticComplexity',
       'SyntacticallyReachableFunctions', 'SemanticallyReachedFunctions',
       'CoverageEstimation', 'SCALAR_INPUT', 'RANGE_SCALAR_VALUES',
       'SCALAR_INDEX_INPUT', 'RANGE_SCALAR_INDEX_VALUES', 'ARRAY_INPUT',
       'RANGE_ARRAY_INPUT', 'cInstr', 'assemblyInstr', 'clockCycles', 'CC4CS',
       'Bugs_Delivered', 'SS_VAL_1', 'SV_VAL_1', 'SV_VAL_2'],
      dtype='object')

In [26]:
dfTot3 = pd.merge(dfTot2,dfVTot,how='left',on=['DEVICE','BOARD','FUNCTION','DATA_TYPE','ID_VAL'])

In [27]:
dfTot3.columns

Index(['DEVICE', 'BOARD', 'FUNCTION', 'DATA_TYPE', 'ID_VAL', 'DSP', 'BRAM',
       'Flip_Flop', 'Area', 'min_Slack', 'Max_Freq', 'Time', 'Energy',
       'BugsDelivered', 'DifficultyLevel', 'DistinctOperands',
       'DistinctOperators', 'Effort', 'ProgramLength', 'ProgramLevel',
       'ProgramVolume', 'TimeToImplement', 'TotalOperators', 'Total_Operands',
       'VocabularySize', 'Sloc', 'DecisionPoint', 'GlobalVariables', 'If',
       'Loop', 'Goto', 'Assignment', 'ExitPoint', 'Function', 'FunctionCall',
       'PointerDereferencing', 'CyclomaticComplexity',
       'SyntacticallyReachableFunctions', 'SemanticallyReachedFunctions',
       'CoverageEstimation', 'SCALAR_INPUT', 'RANGE_SCALAR_VALUES',
       'SCALAR_INDEX_INPUT', 'RANGE_SCALAR_INDEX_VALUES', 'ARRAY_INPUT',
       'RANGE_ARRAY_INPUT', 'cInstr', 'assemblyInstr', 'clockCycles', 'CC4CS',
       'Bugs_Delivered', 'SS_VAL_1', 'SV_VAL_1', 'SV_VAL_2', 'V_VAL_1',
       'V_VAL_2', 'V_VAL_3', 'V_VAL_4', 'V_VAL_5', 'V_VAL_6', 'V_VAL_7',
       'V_VAL_8', 'V_VAL_9', 'V_VAL_10', 'V_VAL_11', 'V_VAL_12', 'V_VAL_13',
       'V_VAL_14', 'V_VAL_15', 'V_VAL_16', 'V_VAL_17', 'V_VAL_18', 'V_VAL_19',
       'V_VAL_20', 'V_VAL_21', 'V_VAL_22', 'V_VAL_23', 'V_VAL_24', 'V_VAL_25',
       'V_VAL_26', 'V_VAL_27', 'V_VAL_28'],
      dtype='object')

In [28]:
dfTot4 = pd.merge(dfTot3,dfMTot,how='left',on=['DEVICE','BOARD','FUNCTION','DATA_TYPE','ID_VAL'])

In [29]:
dfTot4.columns

Index(['DEVICE', 'BOARD', 'FUNCTION', 'DATA_TYPE', 'ID_VAL', 'DSP', 'BRAM',
       'Flip_Flop', 'Area', 'min_Slack',
       ...
       'M_VAL_23', 'M_VAL_24', 'M_VAL_25', 'M_VAL_26', 'M_VAL_27', 'M_VAL_28',
       'M_VAL_29', 'M_VAL_30', 'M_VAL_31', 'M_VAL_32'],
      dtype='object', length=114)

In [30]:
dfTot5 = dfTot4.fillna(0)

In [31]:
dfTot5.to_csv("TotalParameterMatrixBambuValue.csv", sep=';')

In [32]:
# Matrici divise per board

In [33]:
df1 = dfTot5.loc[(dfTot5['BOARD'] == '5SGXEA7N2F45C1-Stratix-V')]
df1.to_csv("TotalParameterMatrixBambuValue_Stratix.csv", sep=';')

In [34]:
df2 = dfTot5.loc[(dfTot5['BOARD'] == 'xc7a100t-1csg324-Artix-7')]
df2.to_csv("TotalParameterMatrixBambuValue_Artix.csv", sep=';')

In [35]:
df3 = dfTot5.loc[(dfTot5['BOARD'] == 'xc7vx690t-3ffg1930-Virtex-7')]
df3.to_csv("TotalParameterMatrixBambuValue_Virtex.csv", sep=';')

In [36]:
df4 = dfTot5.loc[(dfTot5['BOARD'] == 'xc7z020-1clg484-Zynq-7000')]
df4.to_csv("TotalParameterMatrixBambuValue_Zynq.csv", sep=';')

In [37]:
####################### CODICE UTILE DA QUI IN POI ##########################################

In [38]:
dfBamb = dfTot.loc[(dfTot['DEVICE'] == 'Bambu') & (dfTot['BOARD'] == 'xc7a100t-1csg324-Artix-7')]

NameError: name 'dfTot' is not defined

In [39]:
dfBamb.groupby(['DEVICE','BOARD','FUNCTION']).count()

NameError: name 'dfBamb' is not defined

In [40]:
dfBamb.loc[dfTot['FUNCTION'] == 'gcd'].groupby(['DEVICE','BOARD','FUNCTION','DATA_TYPE']).count()

NameError: name 'dfBamb' is not defined